Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [1]:
import numpy as np

# 1. Initialize an empty 2x2 array
empty_array = np.empty((2, 2))
print("Empty Array (2x2):")
print(empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array (4x2):")
print(ones_array)

# 3. Return a new array filled with a specific value (e.g., 7)
full_array = np.full((3, 3), 7)
print("\nFull Array (3x3, filled with 7):")
print(full_array)

# 4. Return a new array of zeros with the same shape and type as the given array
reference_array = np.array([[1, 2], [3, 4]])
zeros_array = np.zeros_like(reference_array)
print("\nZeros Array (same shape as reference):")
print(zeros_array)

# 5. Return a new array of ones with the same shape and type as the given array
ones_array_like = np.ones_like(reference_array)
print("\nOnes Array (same shape as reference):")
print(ones_array_like)

# 6. Convert a list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:")
print(numpy_array)


Empty Array (2x2):
[[4.81090097e-310 0.00000000e+000]
 [2.90435030e-144 6.90090927e-310]]

All Ones Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full Array (3x3, filled with 7):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array (same shape as reference):
[[0 0]
 [0 0]]

Ones Array (same shape as reference):
[[1 1]
 [1 1]]

Converted NumPy Array:
[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [2]:
import numpy as np

# 1. Create an array from 10 to 49
array_10_49 = np.arange(10, 50)
print("Array from 10 to 49:")
print(array_10_49)

# 2. Create a 3x3 matrix with values from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:")
print(matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:")
print(identity_matrix)

# 4. Create a random array of size 30 and find its mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30 and its mean:")
print(random_array)
print("Mean:", mean_value)

# 5. Create a 10x10 random array and find the minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array, Min and Max values:")
print(random_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th element replaced by 1:")
print(zero_array)

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:")
print(reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on the border and 0 inside:")
print(border_array)

# 9. Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Matrix:")
print(checkerboard)


Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30 and its mean:
[0.64921906 0.92876067 0.18672209 0.2869437  0.19707014 0.40102874
 0.89059977 0.3137795  0.34649342 0.18944393 0.00562685 0.04740639
 0.44755047 0.59538851 0.47350335 0.02125652 0.638952   0.53812209
 0.16116119 0.00498084 0.60002672 0.66933306 0.7280703  0.7454779
 0.02155487 0.47596479 0.26840138 0.58993035 0.68421002 0.241468  ]
Mean: 0.41161488746862823

10x10 Random Array, Min and Max values:
[[0.89226371 0.14935881 0.49719935 0.75959167 0.76377984 0.12501743
  0.44749207 0.83734195 0.13416018 0.96425016]
 [0.99754402 0.10355865 0.32320317 0.78992625 0.58691436 0.44979366
  0.26403431 0.06574959 0.35235624 0.91417717]
 [0.32657019 0.82650293 0.62163999 0.29150279 0.47693305 0.39

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [3]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
sum_array = x + y
print("Sum of x and y:")
print(sum_array)

# 2. Subtract the two arrays
difference_array = x - y
print("\nDifference of x and y:")
print(difference_array)

# 3. Multiply the array with an integer of choice
multiplication_result = x * 3
print("\nArray x multiplied by 3:")
print(multiplication_result)

# 4. Find the square of each element of the array
squared_array = np.square(x)
print("\nSquare of each element of array x:")
print(squared_array)

# 5. Find the dot product between: v and w, x and v, x and y
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

print("\nDot product of v and w:", dot_v_w)
print("Dot product of x and v:", dot_x_v)
print("Dot product of x and y:", dot_x_y)

# 6. Concatenate x and y along rows, and v and w along columns
concat_x_y_row = np.concatenate((x, y), axis=1)
print("\nConcatenate x and y along rows:")
print(concat_x_y_row)

v_w_column = np.vstack((v, w))
print("\nConcatenate v and w along columns:")
print(v_w_column)

# 7. Concatenate x and v
try:
    concat_x_v = np.concatenate((x, v), axis=1)
    print("\nConcatenate x and v:")
    print(concat_x_v)
except Exception as e:
    print("\nError in concatenating x and v:")
    print(e)

# Reshape v and concatenate
v_reshaped = v.reshape(-1, 1)
concat_x_v = np.concatenate((x, v_reshaped), axis=1)
print("\nConcatenate reshaped x and v along rows:")
print(concat_x_v)


Sum of x and y:
[[ 6  8]
 [10 13]]

Difference of x and y:
[[-4 -4]
 [-4 -3]]

Array x multiplied by 3:
[[ 3  6]
 [ 9 15]]

Square of each element of array x:
[[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]

Concatenate x and y along rows:
[[1 2 5 6]
 [3 5 7 8]]

Concatenate v and w along columns:
[[ 9 10]
 [11 12]]

Error in concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Concatenate reshaped x and v along rows:
[[ 1  2  9]
 [ 3  5 10]]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [4]:
import numpy as np

# 1. Create an array with values from 10 to 49
arr_10_49 = np.arange(10, 50)
print("Array from 10 to 49:")
print(arr_10_49)

# 2. Create a 3x3 matrix with values from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:")
print(matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:")
print(identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30:")
print(random_array)
print("\nMean of the array:", mean_value)

# 5. Create a 10x10 array with random values and find the min and max values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array:")
print(random_10x10)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th element replaced by 1:")
print(zero_array)

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print("\nReversed Array:")
print(reversed_array)

# 8. Create a 2D array with 1 on the border and 0 inside
size = 5  # Example for a 5x5 matrix
border_array = np.ones((size, size))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on border and 0 inside:")
print(border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:")
print(checkerboard)


Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
[0.11127239 0.06728791 0.9774473  0.20398632 0.33141603 0.70906536
 0.04770879 0.79739261 0.20706129 0.69180322 0.41192658 0.80409233
 0.43709541 0.4092269  0.83972248 0.80905974 0.06715789 0.13768631
 0.85956133 0.31874962 0.01686982 0.62304028 0.31309955 0.23251251
 0.80249296 0.78483223 0.58749825 0.09198036 0.09441055 0.00779807]

Mean of the array: 0.42644181284642696

10x10 Random Array:
[[0.73708981 0.23884839 0.25080934 0.17405334 0.64625096 0.29314615
  0.8302773  0.33220434 0.51943601 0.09566516]
 [0.20933927 0.94793228 0.30191676 0.72501256 0.09398626 0.41069716
  0.47588191 0.13048118 0.82924896 0.5442518 ]
 [0.7851205  0.52651027 0.51786001 0.41326406 0.38336231 0.83567353
  0.6502830