Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

empty_array = np.empty((2, 2))
print("Empty Array :")
print(empty_array)

ones_array = np.ones((4, 2))
print("\nAll Ones Array :")
print(ones_array)

full_array = np.full((3, 3), 7)
print("\nFull Array :")
print(full_array)

reference_array = np.array([[1, 2], [3, 4]])
zeros_array = np.zeros_like(reference_array)
print("\nZeros Array :")
print(zeros_array)

ones_array_like = np.ones_like(reference_array)
print("\nOnes Array :")
print(ones_array_like)

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:")
print(numpy_array)


Empty Array :
[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

All Ones Array :
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full Array :
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array :
[[0 0]
 [0 0]]

Ones Array :
[[1 1]
 [1 1]]

Converted NumPy Array:
[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

array_10_49 = np.arange(10, 50)
print("Array from 10 to 49:")
print(array_10_49)


matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:")
print(matrix_3x3)


identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:")
print(identity_matrix)


random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30 and its mean:")
print(random_array)
print("\nMean:", mean_value)


random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array, Min and Max values:")
print(random_10x10)
print("\nMinimum Value:", min_value)
print("\nMaximum Value:", max_value)


zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th element replaced by 1:")
print(zero_array)


arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:")
print(reversed_arr)


border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on the border and 0 inside:")
print(border_array)


checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Matrix:")
print(checkerboard)


Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30 and its mean:
[0.99534056 0.11553995 0.03734169 0.18565768 0.43589826 0.59447646
 0.4765386  0.45075785 0.62836476 0.65777868 0.00423532 0.88834895
 0.65684913 0.80418638 0.03513082 0.9196576  0.97145347 0.95704554
 0.60288238 0.77846264 0.1229669  0.70155911 0.23477848 0.42632466
 0.90245978 0.25712668 0.7801339  0.54110122 0.19849266 0.49874384]

Mean: 0.5286544651006101

10x10 Random Array, Min and Max values:
[[3.59857140e-01 4.11616153e-01 1.78470213e-01 4.40587713e-01
  5.97677307e-01 7.02150023e-01 6.83997588e-02 5.76186352e-01
  5.88745011e-01 4.57376891e-01]
 [9.00103776e-01 8.31247636e-02 4.96986180e-01 4.18485039e-01
  3.98683160e-01 5.23846433e-01 6.41728644e-01 5.39404338e-01
  3.89943

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])


sum_array = x + y
print("Sum of x and y:")
print(sum_array)

difference_array = x - y
print("\nDifference of x and y:")
print(difference_array)

multiplication_result = x * 3
print("\nArray x multiplied by 3:")
print(multiplication_result)


squared_array = np.square(x)
print("\nSquare of each element of array x:")
print(squared_array)

dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

print("\nDot product of v and w:", dot_v_w)
print("Dot product of x and v:", dot_x_v)
print("Dot product of x and y:", dot_x_y)


concat_x_y_row = np.concatenate((x, y), axis=1)
print("\nConcatenate x and y along rows:")
print(concat_x_y_row)

v_w_column = np.vstack((v, w))
print("\nConcatenate v and w along columns:")
print(v_w_column)

try:
    concat_x_v = np.concatenate((x, v), axis=1)
    print("\nConcatenate x and v:")
    print(concat_x_v)
except Exception as e:
    print("\nError in concatenating x and v:")
    print(e)


v_reshaped = v.reshape(-1, 1)
concat_x_v = np.concatenate((x, v_reshaped), axis=1)
print("\nConcatenate reshaped x and v along rows:")
print(concat_x_v)


Sum of x and y:
[[ 6  8]
 [10 13]]

Difference of x and y:
[[-4 -4]
 [-4 -3]]

Array x multiplied by 3:
[[ 3  6]
 [ 9 15]]

Square of each element of array x:
[[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]

Concatenate x and y along rows:
[[1 2 5 6]
 [3 5 7 8]]

Concatenate v and w along columns:
[[ 9 10]
 [11 12]]

Error in concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Concatenate reshaped x and v along rows:
[[ 1  2  9]
 [ 3  5 10]]


For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)


In [3]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
inverse=np.linalg.inv(A)
# print("Inverse of A: \n",inverse)
dotproduct=np.dot(A,inverse)
print(dotproduct)

c=np.dot(A,B)
print("AB: \n",c)
d=np.dot(B,A)
print("BA: \n",d)
print("Hence AB doesnt equal BA")

e=np.dot(A,B)
transpose1=np.transpose((e))
print("(AB)^t: \n",transpose1)

transpose2=np.transpose((A))
transpose3=np.transpose((B))
f=np.dot(transpose3,transpose2)
print("B^t.A^t: \n", f)
print("Hence prove (AB)^t = B^tA^t.")

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB: 
 [[23 13]
 [51 29]]
BA: 
 [[36 44]
 [13 16]]
Hence AB doesnt equal BA
(AB)^t: 
 [[23 51]
 [13 29]]
B^t.A^t: 
 [[23 51]
 [13 29]]
Hence prove (AB)^t = B^tA^t.


1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [1]:
import time
import numpy as np

# Size for element-wise operations
size = 1000000

# Create two lists of size 1,000,000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# 1. Element-wise Addition using Python Lists
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print(f"Time taken for element-wise addition using Python lists: {end_time - start_time} seconds")

# Element-wise Addition using NumPy Arrays
array1 = np.arange(size)
array2 = np.arange(size)
start_time = time.time()
result_numpy = array1 + array2
end_time = time.time()
print(f"Time taken for element-wise addition using NumPy arrays: {end_time - start_time} seconds")

# 2. Element-wise Multiplication using Python Lists
start_time = time.time()
result_multiply_list = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print(f"Time taken for element-wise multiplication using Python lists: {end_time - start_time} seconds")

# Element-wise Multiplication using NumPy Arrays
start_time = time.time()
result_multiply_numpy = array1 * array2
end_time = time.time()
print(f"Time taken for element-wise multiplication using NumPy arrays: {end_time - start_time} seconds")

# 3. Dot Product using Python Lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print(f"Time taken for dot product using Python lists: {end_time - start_time} seconds")

# Dot Product using NumPy Arrays
start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
end_time = time.time()
print(f"Time taken for dot product using NumPy arrays: {end_time - start_time} seconds")

# 4. Matrix Multiplication using Python Lists
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]
matrix2 = [[i - j for j in range(1000)] for i in range(1000)]

start_time = time.time()
result_matrix_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
end_time = time.time()
print(f"Time taken for matrix multiplication using Python lists: {end_time - start_time} seconds")

# Matrix Multiplication using NumPy Arrays
matrix1_numpy = np.random.rand(1000, 1000)
matrix2_numpy = np.random.rand(1000, 1000)

start_time = time.time()
result_matrix_numpy = np.dot(matrix1_numpy, matrix2_numpy)
end_time = time.time()
print(f"Time taken for matrix multiplication using NumPy arrays: {end_time - start_time} seconds")


Time taken for element-wise addition using Python lists: 0.1865234375 seconds
Time taken for element-wise addition using NumPy arrays: 0.011217355728149414 seconds
Time taken for element-wise multiplication using Python lists: 0.34647297859191895 seconds
Time taken for element-wise multiplication using NumPy arrays: 0.010334491729736328 seconds
Time taken for dot product using Python lists: 0.2144782543182373 seconds
Time taken for dot product using NumPy arrays: 0.0012140274047851562 seconds
Time taken for matrix multiplication using Python lists: 160.0836877822876 seconds
Time taken for matrix multiplication using NumPy arrays: 0.058370351791381836 seconds
